### ISSUE TITLE
Custom font for markdown tabs

### ISSUE THREAD

**Issue by andya9** [burodepeper/language-markdown#177]
Would it be possible to allow users to choose a different font (from the default) for markdown tabs only? The idea is to allow using a monospace font for programming but nicely shifting to a sans or serif when writing prose.

**Comment by burodepeper** [comment]
Have a look at [this comment](https://github.com/atom/language-gfm/issues/69#issuecomment-250648230) and read the rest of the thread as background. The code examples aren't up-to-date anymore, but it's a start if you wish to try some things.

In short: this is an issue related to Atom, not language-markdown. I haven't tried it out myself, but according to the thread I linked, you should be able to whip up something for yourself.

**Comment by andya9** [comment]
Oh, thank'you very much for providing the link & explanation, I appreciate this.

**Comment by kouichi-c-nakamura** [comment]
Currently (1.19.0), adding the following to the `styles.less` file is practically working for me, but I'm not sure it's the best way.

```scss
// language-gfm (builtin)
atom-text-editor[data-grammar="source gfm"],
atom-text-editor[data-grammar="source gfm"].editor {
    font-family: "Open Sans";
}

// language-markdown
// Scope: text.md
atom-text-editor[data-grammar="text md"],
atom-text-editor[data-grammar="text md"].editor {
    font-family: "Open Sans";
}
```
