### ISSUE TITLE
Show line number and git status along line numbers

### ISSUE THREAD

**Issue by daijiang** [burodepeper/language-markdown#186]
Hi, 
Thanks for your great work on this awesome package. I wonder is there a way to show the line numbers and git status along the line numbers (add, delete, change, etc.)? I cannot see any option in the setting about how to do this. It would be really useful if you can add this as an option.
Cheers,
Daijiang

**Comment by burodepeper** [comment]
Thank you!

Could you post a screenshot that illustrates what you're looking for?

**Comment by daijiang** [comment]
Something like this (when disable language-markdown package):
![markdown-with-line-numbers](https://user-images.githubusercontent.com/1696911/28137868-c34743cc-671c-11e7-81ce-5c0ac8572ef2.png)

With the package enable, the main text will be centered (which is great) but no line numbers and git status anymore. It would be great to not hide them. Any ideas?

![no-line-numbers-anymore](https://user-images.githubusercontent.com/1696911/28138013-49de4264-671d-11e7-9a0f-832eae1e1bf2.png)

**Comment by daijiang** [comment]
I figured out it is because of the `typewriter` package I installed, which automatically hide them... Sorry for bothering you!

**Comment by burodepeper** [comment]
Haha, I just wanted to ask if you were also using `typewriter` ; ) Don't worry about it!

**Comment by daijiang** [comment]
A different quick question (thus don't want to open another issue), is it able to highlight latex math equation in Rmarkdown file? I did not get any color highlighting...

![image](https://user-images.githubusercontent.com/1696911/28138458-d80fc6d8-671e-11e7-9b39-63ab6f75fc98.png)

Thanks for your help!

**Comment by burodepeper** [comment]
If you have `language-latex` installed, it should automatically highlight your inline math.

**Comment by daijiang** [comment]
Yes, I have it installed and enabled, but nothing showed up...it is weird.

**Comment by burodepeper** [comment]
It could be that your syntax theme doesn't know how to style latex. Which one are you using?

**Comment by daijiang** [comment]
Good to know, I am using `Base16 Tomorrow Dark`.  I also tried `Atom Dark`, which still does not work.

**Comment by burodepeper** [comment]
Yep, both of them do not style the latex. Your latex example doesn't have a lot to style actually, which might just be bad luck. I have a syntax theme `minimal-syntax-dark` that adds some basic styling to latex. In this case, it should style the `$` delimiters and the curly braces.

Are you a little familiar with CSS? If so, it's not to difficult to add some custom styles yourself.

**Comment by daijiang** [comment]
Thanks, I know a little bit CSS. You mean add a style for the theme? Any resource about how-to?

**Comment by burodepeper** [comment]
Yes, you can extend the styles for a theme. Have a look at [this page](http://flight-manual.atom.io/using-atom/sections/basic-customization/#style-tweaks). It's not incredibly detailed, but who knows it might just be enough.

It's getting late over here (11pm) so I'm off for now. Just post your questions here if you run into any other issues. I'll look at them tomorrow.

**Comment by daijiang** [comment]
Thanks! I really appreciate your help!

**Comment by burodepeper** [comment]
Any luck with your custom styles?

**Comment by daijiang** [comment]
Yes, after copying codes from your `minimal-syntax-dark` and `pen-paper-coffee` theme, I managed to highlight math equation in rmd with `Base16-tomorrow-dark` theme. Here are the code:

```css
@green:         #00FF00;
@red:           #c16161;
@orange:        #d08e25;

&.syntax--math {
  .syntax--support {
    color: darken(@green, 5%);
  }

  .syntax--punctuation.syntax--arguments{
    color: lighten(@red, 5%);
  }

  .syntax--tex {
    &.syntax--constant {
      color: @orange;
      &.syntax--numeric {
        color: @green;
      }
    }
  }

  background: transparent;
  color: darken(@green, 15%);
}
```

One question: how to highlight the `$` or `$$` sign with different color than the math equation per se? Currently, they are highlighted in the same color. Thanks!
